# Fly.io configuration for ProspectAI

app = "prospectai-website"
primary_region = "cdg"

[build]
  builder = "heroku"
  buildpacks = ["heroku/nodejs"]

[env]
  NODE_ENV = "production"
  ADMIN_EMAIL = "sully.capron@synolia.com"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[checks]
  [checks.alive]
    type = "http"
    interval = "30s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/api/health"

